POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk2NTY3ODgsInVzZXJJZCI6MX0.7b4esrFfNaUEOexv0hLTVTgQB0f-ES4iO759z5B-L-M

{
  "name": "Test event",
  "description": "Test event!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
