DELETE http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk2NTUyNDUsInVzZXJJZCI6MX0.A-MTykw_WvjOZS9XkvXuDETk2xzahN384VjwrhkFziE