PUT http://localhost:8080/events/3
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Njk2NTUyNDUsInVzZXJJZCI6MX0.A-MTykw_WvjOZS9XkvXuDETk2xzahN384VjwrhkFziE

{
  "name": "Updated test event",
  "description": "Updated test event",
  "location": "Test location (updated)",
  "dateTime": "2025-01-01T15:30:00Z"
}